# Generate .pb.[ch] form .proto using nanopb
# include relevant files in project build

# Protobuf definition — change PROTO to use a different .proto file
PROTO := ebike_live_data
PROTO_DIR := proto
NANOPB_DIR := external/nanopb

# no user configurable parts beyond this point

PYTHON = python3
PROTOC = $(PYTHON) $(NANOPB_DIR)/generator/protoc
PROTOC_OPTS =

PROTOBUF_SRC += $(NANOPB_DIR)/pb_encode.c $(NANOPB_DIR)/pb_decode.c $(NANOPB_DIR)/pb_common.c
PROTOBUF_SRC += $(PROTO_DIR)/$(PROTO).pb.c

SRC_FILES += $(PROTOBUF_SRC)
INC_FOLDERS += $(NANOPB_DIR) $(PROTO_DIR)

VPATH = $(PROTO_DIR)

# Generate protobuf at parse time if missing, so .pb.h exists before compilation
ifeq ($(wildcard $(PROTO_DIR)/$(PROTO).pb.c),)
$(shell $(PROTOC) $(PROTOC_OPTS) -I$(PROTO_DIR) --nanopb_out=$(PROTO_DIR) $(PROTO).proto)
endif

# Make rule for incremental rebuilds (when .proto is newer)
$(PROTO_DIR)/.pb-stamp: $(PROTO).proto
	$(PROTOC) $(PROTOC_OPTS) -I$(PROTO_DIR) --nanopb_out=$(PROTO_DIR) $(PROTO).proto
	@touch $(PROTO_DIR)/.pb-stamp

# Link .pb.c/.pb.h to stamp so Make resolves the chain via the .d file paths
$(PROTO_DIR)/$(PROTO).pb.c $(PROTO_DIR)/$(PROTO).pb.h: $(PROTO_DIR)/.pb-stamp
	@true

# export so nrf5_sdk.mk can pick this up and wire it into nRF5 SDK build system
PROTO_STAMP := $(PROTO_DIR)/.pb-stamp
PROTO_SRC_BASENAME := $(PROTO).pb.c

# remove autogenerated code when 'clean' target is called for the main Makefile
.PHONY: proto_clean
proto_clean:
	$(RM) -f $(PROTO_DIR)/*.pb.? $(PROTO_DIR)/.pb-stamp
clean: proto_clean
